[project]
name = 'diffscuss'
version = '2.0.0'
author = 'Edmund Jorgensen'
author_email = 'edmund@hut8labs.com'
packages = [
    'diffscuss',
    'diffscuss.support',
    'diffscuss.mailbox',
]
scripts = ['bin/diffscuss']
url = 'http://github.com/hut8labs/diffscuss/'
license = 'LICENSE.txt'
description = 'Plain-text code review format and tools.'
readme = 'README.md'
requires-python = '>=3.10'
dependencies = [
    'PyGithub>=2',
    'requests>=2',
]
